name: PRs to staging

on: 
  pull_request:
    branches: [staging]
    types: [closed]

jobs:
  merge-staging-to-master:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2    
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"    
    
    - name: Merge staging to master
      run: |
          git fetch --unshallow
          git checkout master
          git pull
          git merge --no-ff staging -m "Auto-merge staging to master"
          git push